query extensions
singhal-ekansh/Depot_App_Rails pull request #7
Opened 2023-04-18 14:16 UTC by singhal-ekansh

2023-04-24 03:55 UTC, harsh-ag requested changes

2023-04-24 03:55 UTC, harsh-ag commented on app/models/product.rb
> +  scope :enabled_products, -> { where(enabled: true) }
rename it to only `enabled`

2023-04-24 03:55 UTC, harsh-ag commented on app/models/order.rb
> +  scope :by_date, ( Proc.new do |from, to|
no need to add conditional statements. use default value for arguments

2023-04-26 05:20 UTC, harsh-ag commented on app/models/order.rb
> +  scope :by_date, ( Proc.new do |from = Time.now.midnight, to|
use `-> {}` inplace of Proc.new

2023-04-26 05:46 UTC, singhal-ekansh commented on app/models/order.rb
> +  scope :by_date, ( Proc.new do |from = Time.now.midnight, to|
done

2023-04-26 05:46 UTC, harsh-ag approved these changes

2023-05-02 05:58 UTC, closed without merging